#
# Basic settings.
#
url: http://hjop.kmz-brno.cz
title: hJOP
avatar: /assets/img/hJOP.svg
favicon: /assets/img/hJOP.ico
author: Jan Horáček
robots: index,follow

#
# Icons
#
icons:
  rss: true
  email: jan.horacek@kmz-brno.cz
  github: kmzbrnoI
  bitbucket:
  twitter:
  facebook: kmzbrnoI
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Gems.
#
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

#
# Recent posts.
#
recent_posts_num: 5

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", ".htaccess"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - Makefile

t:
  en:
    description: "A Model Railroad Control Software based on ZTP-JOP"
    keywords: hJOP,JOP,train,model,sw,software
    footer: "<a href='https://github.com/kmzbrnoI/hJOPweb'>This page</a> was created by <a href='http://apophis.cz/'>Jan Horáček</a> using <a href='http://jekyllrb.com'>Jekyll</a> with style <a href='https://github.com/ttskch/jekyll-ttskch-theme'>TtskchTheme</a>."
    str_recent_posts: News
    str_all_posts: All news
  cz:
    description: "Komplexní řešení řízení modelového kolejiště dle ZTP-JOP"
    keywords: hJOP,JOP,vláček,model,sw,program
    footer: "<a href='https://github.com/kmzbrnoI/hJOPweb'>Tuto stránku</a> vytvořil <a href='http://apophis.cz/'>Jan Horáček</a> za použití nástroje <a href='http://jekyllrb.com'>Jekyll</a> a stylu <a href='https://github.com/ttskch/jekyll-ttskch-theme'>TtskchTheme</a>."
    str_recent_posts: Aktuality
    str_all_posts: Všechny aktuality
